### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by zide05** [esdurmus/feqa#3]
I have got error:

WARNING:tensorflow:From /remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/site-packages/benepar/base_parser.py:197: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From /remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/site-packages/benepar/base_parser.py:202: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-10-21 02:43:10.045613: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-10-21 02:43:10.048140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:04:00.0
2020-10-21 02:43:10.049947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:05:00.0
2020-10-21 02:43:10.051732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:08:00.0
2020-10-21 02:43:10.053509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:09:00.0
2020-10-21 02:43:10.055303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 4 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:84:00.0
2020-10-21 02:43:10.057085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 5 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:85:00.0
2020-10-21 02:43:10.058865: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 6 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:88:00.0
2020-10-21 02:43:10.060630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 7 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:89:00.0
2020-10-21 02:43:10.119091: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-10-21 02:43:10.372176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-10-21 02:43:10.689605: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-10-21 02:43:11.367065: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-10-21 02:43:11.797432: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-10-21 02:43:12.109357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-10-21 02:43:12.734638: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-21 02:43:12.776790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7
2020-10-21 02:43:12.777739: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-21 02:43:12.819504: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500020000 Hz
2020-10-21 02:43:12.823778: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5646078273e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-21 02:43:12.823851: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-21 02:43:14.456162: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5645e61c3230 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-21 02:43:14.456224: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-21 02:43:14.456236: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-21 02:43:14.456247: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-21 02:43:14.456258: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-21 02:43:14.456268: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (4): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-21 02:43:14.456282: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (5): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-21 02:43:14.456292: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (6): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-21 02:43:14.456302: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (7): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-21 02:43:14.466843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:04:00.0
2020-10-21 02:43:14.468575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:05:00.0
2020-10-21 02:43:14.470257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:08:00.0
2020-10-21 02:43:14.471930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:09:00.0
2020-10-21 02:43:14.473609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 4 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:84:00.0
2020-10-21 02:43:14.475274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 5 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:85:00.0
2020-10-21 02:43:14.476952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 6 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:88:00.0
2020-10-21 02:43:14.478559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 7 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:89:00.0
2020-10-21 02:43:14.478629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-10-21 02:43:14.478655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-10-21 02:43:14.478677: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-10-21 02:43:14.478698: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-10-21 02:43:14.478727: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-10-21 02:43:14.478749: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-10-21 02:43:14.478772: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-21 02:43:14.509762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7
2020-10-21 02:43:14.509926: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-10-21 02:43:14.532018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-21 02:43:14.532129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 2 3 4 5 6 7 
2020-10-21 02:43:14.532172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N N N N N N N 
2020-10-21 02:43:14.532191: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N N N N N N N 
2020-10-21 02:43:14.532210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 2:   N N N N N N N N 
2020-10-21 02:43:14.532233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 3:   N N N N N N N N 
2020-10-21 02:43:14.532258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 4:   N N N N N N N N 
2020-10-21 02:43:14.532279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 5:   N N N N N N N N 
2020-10-21 02:43:14.532305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 6:   N N N N N N N N 
2020-10-21 02:43:14.532326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 7:   N N N N N N N N 
2020-10-21 02:43:14.558209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10310 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:04:00.0, compute capability: 7.5)
2020-10-21 02:43:14.561528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10310 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:05:00.0, compute capability: 7.5)
2020-10-21 02:43:14.564836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10310 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080 Ti, pci bus id: 0000:08:00.0, compute capability: 7.5)
2020-10-21 02:43:14.567993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10310 MB memory) -> physical GPU (device: 3, name: GeForce RTX 2080 Ti, pci bus id: 0000:09:00.0, compute capability: 7.5)
2020-10-21 02:43:14.571276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 10310 MB memory) -> physical GPU (device: 4, name: GeForce RTX 2080 Ti, pci bus id: 0000:84:00.0, compute capability: 7.5)
2020-10-21 02:43:14.574422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 10310 MB memory) -> physical GPU (device: 5, name: GeForce RTX 2080 Ti, pci bus id: 0000:85:00.0, compute capability: 7.5)
2020-10-21 02:43:14.577597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 10310 MB memory) -> physical GPU (device: 6, name: GeForce RTX 2080 Ti, pci bus id: 0000:88:00.0, compute capability: 7.5)
2020-10-21 02:43:14.580785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 10310 MB memory) -> physical GPU (device: 7, name: GeForce RTX 2080 Ti, pci bus id: 0000:89:00.0, compute capability: 7.5)
Generating questions...
2020-10-21 02:43:26.130147: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
Getting answers...
10/21/2020 02:43:47 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 8, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "./qa_models/squad1.0/run_squad.py", line 820, in <module>
    main()
  File "./qa_models/squad1.0/run_squad.py", line 745, in main
    model.to(args.device)
  File "/remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 443, in to
    return self._apply(convert)
  File "/remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 441, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: out of memory
Traceback (most recent call last):
  File "test_feqa.py", line 24, in <module>
    scorer.compute_score(documents, summaries, aggregate=False)
  File "/remote-home/yrchen/tasks/summarization/feqa/feqa.py", line 184, in compute_score
    predictions_dict = self._run_squad(squad_format)
  File "/remote-home/yrchen/tasks/summarization/feqa/feqa.py", line 149, in _run_squad
    ret = subprocess.check_output(cmd, shell=True)
  File "/remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/remote-home/yrchen/anaconda3/envs/pytorch1.5_p37/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python ./qa_models/squad1.0/run_squad.py --model_type bert --model_name_or_path ./qa_models/squad1.0 --do_eval --overwrite_cache --do_lower_case --predict_file /tmp/tmpro7mmb3q/squad_input.json --per_gpu_train_batch_size 12 --max_seq_length 384 --doc_stride 128 --output_dir /tmp/tmpro7mmb3q' returned non-zero exit status 1.

when using linux with 8 GeForce RTX 2080 Ti
what is your gpu version when running 
`scorer = FEQA(use_gpu=False)`
`scorer.compute_score(documents, summaries, aggregate=False)`

**Comment by OrangeInSouth** [comment]
Hi!
I have the same problem. Could you tell me how to deal with it?

**Comment by s103321048** [comment]
I also have the same problem... Is there a solution?
No matter I set use_gpu to True or False, they both run on gpu and both got CUDA memory error.

**Comment by xwjim** [comment]
> This issue still persists, even at a batch size of 1 CUDA runs out of memory quite easily

Do you know how to solve the problem?

**Comment by Lukecn1** [comment]
> > This issue still persists, even at a batch size of 1 CUDA runs out of memory quite easily
> 
> Do you know how to solve the problem?

Yes, in the feqa.py script, change the self.batch_size in the constructor to a lower value than 64. 

While this "fixed" it for me, FEQA inference time is still quite long, and requires significant amounts of compute.

**Comment by xwjim** [comment]
> > > This issue still persists, even at a batch size of 1 CUDA runs out of memory quite easily
> > 
> > 
> > Do you know how to solve the problem?
> 
> Yes, in the feqa.py script, change the self.batch_size in the constructor to a lower value than 64.
> 
> While this "fixed" it for me, FEQA inference time is still quite long, and requires significant amounts of compute.

Thanks a lot.
